package com.websystique.springmvc.model;
// Generated Sep 8, 2017 3:12:32 PM by Hibernate Tools 4.3.1



/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private String marca;
     private String modelo;
     private String ano;
     private String serie;
     private String ficha;

    public Equipos() {
    }

	
    public Equipos(String serie, String ficha) {
        this.serie = serie;
        this.ficha = ficha;
    }
    public Equipos(String tipo, String marca, String modelo, String ano, String serie, String ficha) {
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.ano = ano;
       this.serie = serie;
       this.ficha = ficha;
    }
    
     public Equipos(int id, String tipo, String marca, String modelo, String ano, String serie, String ficha) {
       this.id = id;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.ano = ano;
       this.serie = serie;
       this.ficha = ficha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getFicha() {
        return this.ficha;
    }
    
    public void setFicha(String ficha) {
        this.ficha = ficha;
    }




}


