package com.websystique.springmvc.model;
// Generated Sep 8, 2017 3:12:32 PM by Hibernate Tools 4.3.1



/**
 * Ordenes generated by hbm2java
 */
public class Ordenes  implements java.io.Serializable {


     private Integer id;
     private String fechaCreacion;
     private String fechaCierre;
     private String tipoOrden;
     private String descripcion;
     private Integer equipoFk;
     private String estatus;

    public Ordenes() {
    }

    public Ordenes(String fechaCreacion, String fechaCierre, String tipoOrden, String descripcion, Integer equipoFk, String estatus) {
       this.fechaCreacion = fechaCreacion;
       this.fechaCierre = fechaCierre;
       this.tipoOrden = tipoOrden;
       this.descripcion = descripcion;
       this.equipoFk = equipoFk;
       this.estatus = estatus;
    }
    
      public Ordenes(int id,String fechaCreacion, String fechaCierre, String tipoOrden, String descripcion, Integer equipoFk, String estatus) {
       this.id = id;
       this.fechaCreacion = fechaCreacion;
       this.fechaCierre = fechaCierre;
       this.tipoOrden = tipoOrden;
       this.descripcion = descripcion;
       this.equipoFk = equipoFk;
       this.estatus = estatus;
    }
   
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(String fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public String getTipoOrden() {
        return this.tipoOrden;
    }
    
    public void setTipoOrden(String tipoOrden) {
        this.tipoOrden = tipoOrden;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEquipoFk() {
        return this.equipoFk;
    }
    
    public void setEquipoFk(Integer equipoFk) {
        this.equipoFk = equipoFk;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


